alias dev='ssh acousin@94.23.17.135'
alias prod='ssh acousin@ns3269944.ovh.net'
alias checkme='cd /home/laravel/checkme'
alias debugcheckme='DEBUG=checkme ./bin/www'
alias sassdev='sass-convert {global,index,login}.{sass,scss}; sass --update .:.; rsync *.css* acousin@94.23.17.135:/home/laravel/checkme/public/stylesheets/; rsync *.sass acousin@94.23.17.135:/home/laravel/checkme/sass'
alias androidstudio='/home/alexandre/apps/android-studio/bin/studio.sh'
alias pickonserv='cd /mnt/affaircry/007_PROJETS_INNOVATION_CONSEIL/201311_FIDZUP/7.\ APPLICATION\ MOBILE/'
alias pickoutios='cd /home/alexandre/Documents/pickout-ios/pickout/Pickout'
alias pickout='cd /home/laravel/pickout'
alias chromiumi='chromium --incognito'
alias gchrome='google-chrome'
alias crysaccess='/home/theodo/crysalide'
